作業目標<br>
計算有缺失值的資料，統計量實作<br>
作業重點<br>
當遇到缺失值有函式可以處理，不須額外寫程式刪除<br>
計算統計量時不能出現缺失值

題目:<br>
english_score = np.array([55,89,76,65,48,70])<br>
math_score = np.array([60,85,60,68,np.nan,60])<br>
chinese_score = np.array([65,90,82,72,66,77])<br>
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。<br>
1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
3. 用補考後資料找出與國文成績相關係數最高的學科?

In [1]:
import numpy as np

In [2]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [25]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
print("--英文成績--")
english_mean = np.nanmean(english_score)
english_max = np.nanmax(english_score)
english_min = np.nanmin(english_score)
english_std = np.nanstd(english_score)
print("平均值：:",english_mean)
print("最大值：:",english_max)
print("最小值：:",english_min)
print("標準差值：:",english_std)
print("--數學成績--")
math_mean = np.nanmean(math_score)
math_max = np.nanmax(math_score)
math_min = np.nanmin(math_score)
math_std = np.nanstd(math_score)
print("平均值：:",math_mean)
print("最大值：:",math_max)
print("最小值：:",math_min)
print("標準差值：:",math_std)
print("--中文成績--")
chinese_mean = np.nanmean(chinese_score)
chinese_max = np.nanmax(chinese_score)
chinese_min = np.nanmin(chinese_score)
chinese_std = np.nanstd(chinese_score)
print("平均值：:",chinese_mean)
print("最大值：:",chinese_max)
print("最小值：:",chinese_min)
print("標準差值：:",chinese_std)

--英文成績--
平均值：: 67.16666666666667
最大值：: 89
最小值：: 48
標準差值：: 13.433995020924426
--數學成績--
平均值：: 66.6
最大值：: 85.0
最小值：: 60.0
標準差值：: 9.707728879609279
--中文成績--
平均值：: 75.33333333333333
最大值：: 90
最小值：: 65
標準差值：: 8.825468196582484


In [43]:
print('[平均]\t英文{0}, 數學:{1}, 國文:{2}'.format(np.nanmean(english_score), np.nanmean(math_score), np.nanmean(chinese_score)))
print('[最大值]\t英文{0}, 數學:{1}, 國文:{2}'.format(np.nanmax(english_score), np.nanmax(math_score), np.nanmax(chinese_score)))
print('[最小值]\t英文{0}, 數學:{1}, 國文:{2}'.format(np.nanmin(english_score), np.nanmin(math_score), np.nanmin(chinese_score)))
print('[標準差]\t英文{0}, 數學:{1}, 國文:{2}'.format(np.nanstd(english_score), np.nanstd(math_score), np.nanstd(chinese_score)))

[平均]	英文67.16666666666667, 數學:64.66666666666667, 國文:75.33333333333333
[最大值]	英文89, 數學:85.0, 國文:90
[最小值]	英文48, 數學:55.0, 國文:65
[標準差]	英文13.433995020924426, 數學:9.860132971832694, 國文:8.825468196582484


In [28]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?

In [31]:
math_score[4] = 55
print("--數學成績--")
math_mean = np.nanmean(math_score)
math_max = np.nanmax(math_score)
math_min = np.nanmin(math_score)
math_std = np.nanstd(math_score)
print("平均值：:",math_mean)
print("最大值：:",math_max)
print("最小值：:",math_min)
print("標準差值：:",math_std)

--數學成績--
平均值：: 64.66666666666667
最大值：: 85.0
最小值：: 55.0
標準差值：: 9.860132971832694


In [5]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?

In [33]:
np.corrcoef([english_score, chinese_score])

array([[1.        , 0.97792828],
       [0.97792828, 1.        ]])

In [34]:
np.corrcoef([math_score, chinese_score])

array([[1.        , 0.74056803],
       [0.74056803, 1.        ]])

In [35]:
np.corrcoef([english_score,math_score, chinese_score])

array([[1.        , 0.7855563 , 0.97792828],
       [0.7855563 , 1.        , 0.74056803],
       [0.97792828, 0.74056803, 1.        ]])